import type { Metadata } from "next";
import Link from "next/link";
import Image from "@/app/_components/asset-image";
import Icon from "@/app/_components/icon";
import { corporateArticles } from "@/content/corporate-articles";
import { testimonials } from "@/content/testimonials";
import PageSectionNav from "../_components/page-section-nav";
import pageLayoutStyles from "../_components/entity-formation-page.module.css";
import styles from "./public-limited-company.module.css";

export const metadata: Metadata = {
  title: "Public Limited Company Registration in India | Astronis Global",
  description: "Plan Public Limited Company incorporation in India with support for formation documents, governance, registrations and ongoing corporate compliance.",
  alternates: { canonical: "/services/corporate-commercial-advisory/entity-formation-business-setup/public-limited-company" },
};

const nav = [["Overview", "overview"], ["Benefits", "benefits"], ["Eligibility & Structure", "eligibility"], ["Process & Timeline", "process"], ["Compliance & Taxation", "taxation"], ["FAQs", "faqs"]];
const services = [
  ["search", "Name Availability & Reservation", "Review proposed names and coordinate reservation."], ["file", "Incorporation & MOA Filing", "Coordinate incorporation documents and ROC filing."], ["document", "Drafting of MOA & AOA", "Prepare constitutional documents around your objects and governance."], ["building", "PAN, TAN & Bank Account Assistance", "Coordinate essential post-incorporation setup."], ["percent", "GST & Statutory Registrations", "Map registrations to your business activity and location."], ["people", "Shareholding & ESOP Advisory", "Plan ownership and employee equity arrangements."], ["shield", "Corporate Compliance Support", "Establish a practical approach to recurring obligations."], ["calendar", "Board Meetings & Resolutions", "Support board processes, records and resolutions."], ["document", "Secretarial Compliance", "Coordinate company law filings and governance records."], ["chart", "Listing Readiness (Pre-IPO Advisory)", "Prepare governance and documentation workstreams for review."], ["globe", "Foreign Investment (FEMA/FDI) Advisory", "Review investment structures and relevant reporting needs."], ["scale", "Ongoing Legal & Regulatory Advisory", "Connect legal and regulatory questions to business decisions."],
];
const benefits = [["chart", "Public and institutional capital", "A share-based structure can support broader capital raising, subject to applicable laws and offer requirements."], ["gem", "Credibility and market reputation", "A formal governance framework can support confidence among counterparties, investors and stakeholders."], ["building", "Stock exchange access", "A public company may pursue listing if it meets the relevant exchange and regulatory requirements."], ["network", "Broader ownership and liquidity", "Shares can be transferable, subject to applicable law and securities regulations."], ["rocket", "Large-scale expansion", "A structure often considered by businesses planning significant growth and investment."], ["shield", "Continuity", "The company has a separate legal identity and perpetual succession." ]];
const comparison = [
  ["Minimum members", "7", "2", "1", "2", "2", "1"], ["Separate legal entity", "Yes", "Yes", "Yes", "Yes", "No", "No"], ["Limited liability", "Yes", "Yes", "Yes", "Yes", "No (unlimited)", "No (unlimited)"], ["Perpetual succession", "Yes", "Yes", "Yes", "Yes", "No", "No"], ["Ease of fundraising", "Very high", "High", "Moderate", "Moderate", "Low", "Low"], ["Compliance requirements", "High (listed / unlisted)", "Moderate to high", "Moderate", "Moderate", "Low", "Low"], ["Suitable for", "Large businesses, IPO, public fundraising", "Growing and scalable businesses", "Single entrepreneur", "Professional services and SMEs", "Small and family businesses", "Individual businesses"], ["Taxation", "Corporate tax rates", "Corporate tax rates", "Corporate tax rates", "Pass-through taxation", "Income taxed in hands of partners", "Income taxed in hands of proprietor"],
];
const process = [["Consultation & structure planning", "Align the proposed structure with ownership, business activity and capital plans."], ["Name reservation", "Usually 1–2 working days, subject to name availability and government processing."], ["Document preparation", "Prepare incorporation details and constitutional documents for review."], ["Filing with ROC", "Filing may take around 6–7 working days, subject to complete documents and authority processing."], ["Certificate of incorporation", "Receive the incorporation certificate after approval."], ["PAN, TAN & registrations", "Coordinate tax identifiers, banking assistance and applicable registrations."], ["Post-incorporation compliance", "Set up records, governance routines and relevant ongoing filings."]];
const documents = ["Proposed company name(s)", "PAN, Aadhaar and address proof of directors", "Passport-size photographs of directors", "Address proof of registered office", "Digital Signature Certificate (DSC)", "Director Identification Number (DIN)", "MOA & AOA (drafted and filed)", "Occupancy proof, rent agreement or NOC (if applicable)", "Consent and declarations under the Companies Act, 2013"];
const requirements = [["people", "Minimum members", "7 members for incorporation"], ["building", "Minimum directors", "3 directors; at least 1 resident in India"], ["chart", "Minimum share capital", "No prescribed minimum; plan capital to suit the business"], ["percent", "Paid-up capital", "As per business requirements"], ["pin", "Registered office", "An address in India with valid supporting proof"]];
const faqs = [["What is a Public Limited Company?", "A Public Limited Company is a company that can offer its shares to the public and may suit larger businesses seeking public funding or stock exchange access, subject to applicable requirements."], ["What is the minimum number of members?", "At least 7 members are required to incorporate a public company."], ["Is listing on a stock exchange mandatory?", "No. A public company may remain unlisted or pursue listing based on its plans and eligibility."], ["What is the minimum capital required?", "There is no prescribed minimum paid-up capital for incorporation. Capital should be considered in light of the business plan and applicable requirements."]];

function Heading({ eyebrow, title, text, light = false }: { eyebrow: string; title: string; text?: string; light?: boolean }) {
  return <div className={`${styles.heading} ${light ? styles.lightHeading : ""}`}><span>{eyebrow}</span><h2>{title}</h2>{text && <p>{text}</p>}</div>;
}

export default function PublicLimitedCompanyPage() {
  const review = testimonials.find((item) => item.status === "approved" && item.publicationConsent && item.service === "Corporate & Commercial Advisory");
  const articles = corporateArticles.slice(0, 3);
  return <div className={styles.page}>
    <section className={styles.hero} id="overview">
      <Image src="/corporate-regulatory-hero.png" alt="Corporate professionals reviewing a business strategy" fill priority sizes="(max-width: 850px) 100vw, 50vw" className={styles.heroImage} />
      <div className={`container ${styles.heroInner}`}>
        <nav className={styles.breadcrumb} aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/services">Services</Link><span>/</span><Link href="/services/corporate-commercial-advisory">Corporate &amp; Commercial</Link><span>/</span><Link href="/services/corporate-commercial-advisory#entity-formation-business-setup">Entity Formation &amp; Business Setup</Link><span>/</span><span aria-current="page">Public Limited Company</span></nav>
        <div className={styles.heroCopy}><span className={styles.eyebrow}>CORPORATE &amp; COMMERCIAL ADVISORY · ENTITY FORMATION</span><h1>Public Limited Company</h1><h2>Build for Scale. Access Capital. Grow Beyond Borders.</h2><p>Incorporate with end-to-end legal, regulatory and compliance support—building a considered foundation for a broader shareholder base, future fundraising and sustainable growth.</p><div className={styles.actions}><Link className={styles.primary} href="/professionals/enquiry">Get Started <Icon name="arrow" /></Link><Link className={styles.secondary} href="/contact">Schedule a Consultation <Icon name="calendar" /></Link></div></div>
        <div className={styles.heroNote}><span>FORMATION WITH A LONG VIEW</span><strong>Structure first.<br />Then scale with clarity.</strong><p>One coordinated view of incorporation, governance and what comes next.</p></div>
      </div>
    </section>

    <div className={pageLayoutStyles.pageNavLayout}>
      <div className={pageLayoutStyles.pageContent}>

    <section className={styles.services}><div className="container"><Heading eyebrow="OUR SERVICES FOR PUBLIC LIMITED COMPANY" title="A coordinated path from incorporation to scale" text="Public Limited Company registration is the starting point. Our team can coordinate the connected legal, governance and regulatory workstreams."/><div className={styles.serviceGrid}>{services.map(([icon, title, text]) => <article className={styles.serviceCard} key={title}><span className={styles.icon}><Icon name={icon}/></span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

    <section className={styles.benefits} id="benefits"><div className={`container ${styles.benefitLayout}`}><div><Heading eyebrow="KEY BENEFITS" title="Why choose a Public Limited Company?" text="For businesses with the scale, governance capacity and ambitions to consider a broader ownership structure."/><div className={styles.benefitGrid}>{benefits.map(([icon, title, text]) => <article key={title}><span className={styles.icon}><Icon name={icon}/></span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></div><aside className={styles.benefitPanel}><span>GOVERNANCE THAT SUPPORTS GROWTH</span><h3>A stronger platform for the next chapter.</h3><p>Public company formation should reflect how the business intends to operate, make decisions and engage with investors over time.</p><Link href="/services/corporate-commercial-advisory#entity-formation-business-setup">Explore entity formation <Icon name="arrow"/></Link></aside></div></section>

    <section className={styles.tax} id="taxation"><div className={`container ${styles.taxGrid}`}><div><Heading eyebrow="BUSINESS STRUCTURE & TAXATION SUPPORT" title="Built for a wider business horizon" text="A Public Limited Company provides a robust framework for larger businesses to organise capital, governance and access to domestic and international markets." light/><ul className={styles.taxPoints}>{[["percent", "Corporate taxation", "Taxed separately as a company under applicable corporate tax rules."], ["gem", "Deductions and incentives", "Eligibility depends on the activity, facts and current tax provisions."], ["scale", "Public funding rules", "Public offers, IPOs and listings bring additional regulatory requirements."], ["globe", "Institutional & foreign investment", "A familiar corporate form for many institutional and overseas investors, subject to applicable rules."]].map(([i,t,d])=><li key={t}><Icon name={i}/><div><strong>{t}</strong><p>{d}</p></div></li>)}</ul></div><figure className={styles.taxImage}><Image src="/Part-16 .png" alt="Business leaders discussing corporate finance and expansion" fill sizes="(max-width: 850px) 100vw, 42vw"/><figcaption>Structure for today.<br/><strong>Readiness for tomorrow.</strong></figcaption></figure></div></section>

    <section className={styles.comparison}><div className="container"><Heading eyebrow="COMPARATIVE ANALYSIS" title="Which structure is right for you?" text="A high-level comparison of common business structures. Suitability and tax treatment depend on individual circumstances and current law."/><div className={styles.tableWrap} role="region" aria-label="Business structure comparison table" tabIndex={0}><table><thead><tr>{["Features", "Public Limited Company", "Private Limited Company", "One Person Company (OPC)", "Limited Liability Partnership (LLP)", "Partnership Firm", "Sole Proprietorship Firm"].map((x,i)=><th key={x} className={i===1?styles.focusCol:""}>{x}</th>)}</tr></thead><tbody>{comparison.map(row=><tr key={row[0]}>{row.map((cell,i)=><td key={`${row[0]}-${i}`} className={i===1?styles.focusCol:""}>{cell}</td>)}</tr>)}</tbody></table></div><p className={styles.tableNote}>This comparison is for general information and is not a substitute for advice on your proposed structure.</p></div></section>

    <section className={styles.process} id="process"><div className="container"><Heading eyebrow="INCORPORATION PROCESS" title="Simple, transparent and timely" text="A clear sequence of decisions and filings, coordinated around complete information and authority processing."/><ol className={styles.timeline}>{process.map(([title, desc], i)=><li key={title}><span className={styles.stepNum}>{String(i+1).padStart(2,"0")}</span><span className={styles.stepIcon}><Icon name={["people","search","document","file","award","building","calendar"][i]}/></span><h3>{title}</h3><p>{desc}</p></li>)}</ol></div></section>

    <section className={styles.documents}><div className={`container ${styles.documentGrid}`}><div><Heading eyebrow="DOCUMENTS REQUIRED" title="Key documents for incorporation" text="We will confirm the documents needed for your circumstances and the current filing process."/><ul className={styles.checklist}>{documents.map(d=><li key={d}><Icon name="shield"/>{d}</li>)}</ul></div><div className={styles.documentImage}><Image src="/Part-18 .png" alt="Corporate incorporation documents arranged for review" fill sizes="(max-width: 800px) 100vw, 45vw"/><span>Prepared with care.<br/><strong>Filed with clarity.</strong></span></div></div></section>

    <section className={styles.requirements} id="eligibility"><div className="container"><Heading eyebrow="MINIMUM REQUIREMENTS" title="Members, directors & capital" text="A concise view of the core incorporation requirements for a public company in India."/><div className={styles.requirementGrid}>{requirements.map(([icon,title,text],i)=><article key={title}><span className={styles.requirementIcon}><Icon name={icon}/></span><small>0{i+1}</small><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

    <section className={styles.pricing}><div className="container"><Heading eyebrow="OUR PROFESSIONAL FEES" title="Transparent and value-driven" text="Choose a starting scope. Final fees and government charges depend on the specific requirements and confirmed scope."/><div className={styles.priceGrid}><article className={styles.priceCard}><span>FORMATION ESSENTIALS</span><h3>Basic Package</h3><strong className={styles.price}>₹19,999<small>/-</small></strong><ul>{["Name reservation", "Incorporation with ROC", "MOA & AOA drafting and filing", "PAN, TAN and basic compliance support"].map(x=><li key={x}><Icon name="shield"/>{x}</li>)}</ul><Link className={styles.priceButton} href="/professionals/enquiry">Get Started <Icon name="arrow"/></Link></article><article className={`${styles.priceCard} ${styles.featuredPrice}`}><span>EXTENDED STARTUP SUPPORT</span><h3>Comprehensive Package</h3><strong className={styles.price}>₹29,999<small>/-</small></strong><ul>{["All Basic Package services", "GST registration", "Bank account assistance", "Initial compliance guidance", "Post-incorporation advisory (1 month)"].map(x=><li key={x}><Icon name="shield"/>{x}</li>)}</ul><Link className={styles.priceButton} href="/contact">Schedule a Consultation <Icon name="arrow"/></Link></article><article className={styles.customPrice}><span>FOR COMPLEX REQUIREMENTS</span><h3>Customised Quote</h3><p>For sector-specific licensing, IPO readiness, foreign investment, listing compliance or a complex structure.</p><Link href="/professionals/enquiry">Get a Quote <Icon name="arrow"/></Link></article></div><p className={styles.priceNote}>Professional fees shown above are indicative. Applicable taxes, statutory fees and third-party costs may be additional.</p></div></section>

    <section className={styles.features}><div className="container"><Heading eyebrow="KEY FEATURES" title="A public company, considered carefully" text="Core characteristics to weigh alongside your funding and governance plans." light/><div className={styles.featureStrip}>{[["chart","Public capital"],["gem","Market credibility"],["network","Transferable shares"],["building","Separate legal identity"],["shield","Perpetual succession"],["rocket","Scale & IPO potential"],["award","Brand value"]].map(([i,t])=><div key={t}><Icon name={i}/><span>{t}</span></div>)}</div></div></section>

    <section className={styles.faq} id="faqs"><div className={`container ${styles.faqLayout}`}><div><Heading eyebrow="FREQUENTLY ASKED QUESTIONS" title="A few useful answers" text="Get familiar with the main considerations before beginning a public company incorporation."/><Link href="/faqs">Browse all FAQs <Icon name="arrow"/></Link></div><div className={styles.faqList}>{faqs.map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></div></section>

    {review && <section className={styles.testimonial}><div className="container"><Heading eyebrow="CLIENT PERSPECTIVE" title="Clear advice. Practical direction." text="A perspective shared with permission by a client of our corporate and commercial advisory team."/><figure><span className={styles.quoteMark}>“</span><blockquote>{review.quote}</blockquote><figcaption><strong>{review.name}</strong><span>{review.designation}, {review.company}</span><span className={styles.stars} aria-label={`${review.rating} out of 5 stars`}>{"★".repeat(review.rating || 0)}</span></figcaption></figure></div></section>}

    <section className={styles.insights}><div className="container"><div className={styles.sectionTop}><Heading eyebrow="INSIGHTS" title="Latest articles, updates and events"/><Link href="/insights">View all insights <Icon name="arrow"/></Link></div><div className={styles.articleGrid}>{articles.map(article=><article key={article.slug}><Link href={`/insights/${article.slug}`} className={styles.articleImage}><Image src={article.image} alt="" fill sizes="(max-width: 650px) 100vw, 33vw"/></Link><div><span>{article.category} · Astronis Insights</span><h3><Link href={`/insights/${article.slug}`}>{article.title}</Link></h3><p>{article.excerpt}</p><Link href={`/insights/${article.slug}`} className={styles.readMore}>Read insight <Icon name="arrow"/></Link></div></article>)}</div></div></section>

    <section className={styles.knowledge}><div className="container"><Heading eyebrow="KNOWLEDGE CENTRE" title="Guides, checklists and templates" text="Practical starting points to help organise your incorporation planning."/><div className={styles.resourceGrid}>{[["CHECKLIST","Documents for Public Limited Company","file"],["GUIDE","Step-by-Step Incorporation Process","document"],["TEMPLATE","MOA & AOA for Public Limited Company","folder"]].map(([type,title,icon])=><Link href="/knowledge-centre" key={type}><span className={styles.icon}><Icon name={icon}/></span><small>{type}</small><h3>{title}</h3><span className={styles.resourceAction}>Explore resource <Icon name="arrow"/></span></Link>)}</div></div></section>

    <section className={styles.experience}><div className="container"><Heading eyebrow="SHARE YOUR EXPERIENCE WITH ASTRONIS GLOBAL" title="Your experience matters"/><div className={styles.experienceGrid}><article><Icon name="message"/><div><h3>Write a review</h3><p>Share your experience and help us serve you better.</p></div><Link href="/testimonials">Write a Review <Icon name="arrow"/></Link></article><article><Icon name="play"/><div><h3>Record a video testimonial</h3><p>Share your video feedback about your journey with Astronis Global.</p></div><Link href="/testimonials">Record a Video <Icon name="arrow"/></Link></article></div></div></section>

    <section className={styles.final}><div className="container"><span>YOUR NEXT CHAPTER STARTS HERE</span><h2>Ready to incorporate your Public Limited Company?</h2><p>Let our experts guide you through a seamless and compliant incorporation process.</p><Link href="/contact">Schedule a Consultation <Icon name="arrow"/></Link></div></section>
      </div>
      <PageSectionNav items={nav.map(([label, id]) => ({ id, label }))} />
    </div>
  </div>;
}
