export const clients = [
  { name: "Vedanta", descriptor: "Transforming for good", className: "vedanta" },
  { name: "DLF", descriptor: "Building India", className: "dlf" },
  { name: "Tata", descriptor: "", className: "tata" },
  { name: "Godrej", descriptor: "", className: "godrej" },
  { name: "ITC Limited", descriptor: "", className: "itc" },
  { name: "Flipkart", descriptor: "", className: "flipkart" },
  { name: "Jindal Steel & Power", descriptor: "", className: "jindal" },
  { name: "Max Healthcare", descriptor: "", className: "max" },
  { name: "Adani", descriptor: "", className: "adani" },
  { name: "Maruti Suzuki", descriptor: "", className: "maruti" },
  { name: "Bharti Enterprises", descriptor: "", className: "bharti" },
  { name: "Reliance Industries", descriptor: "Limited", className: "reliance" },
  { name: "HDFC Bank", descriptor: "", className: "hdfc" },
  { name: "ICICI Bank", descriptor: "", className: "icici" },
  { name: "Kotak Mahindra Bank", descriptor: "", className: "kotak" },
  { name: "EY", descriptor: "Building a better working world", className: "ey" },
  { name: "pwc", descriptor: "", className: "pwc" },
  { name: "KPMG", descriptor: "", className: "kpmg" },
  { name: "Grant Thornton", descriptor: "", className: "grant" },
  { name: "Lupin", descriptor: "", className: "lupin" },
  { name: "Sun Pharma", descriptor: "", className: "sun" },
  { name: "Coca-Cola", descriptor: "", className: "coca" },
  { name: "Blue Star", descriptor: "", className: "blue-star" },
  { name: "Wipro", descriptor: "Applying thought", className: "wipro" },
] as const;
