import Link from "next/link";
import Image from "../_components/asset-image";
import Icon from "../_components/icon";
import { industries, serviceFaqs } from "@/content/site";
import { professionals } from "../professionals/leadership";
import { corporateArticles } from "@/content/corporate-articles";
import styles from "./corporate-commercial.module.css";

const capabilities = [
  ["Corporate Structuring", "Entity structuring, group reorganisation and strategic business structuring.", "corporate-advisory/corporate-structuring", "Real Estate & Construction .png"],
  ["Corporate Governance", "Board advisory, governance frameworks and ongoing compliance support.", "corporate-advisory/corporate-governance", "Part-10 .png"],
  ["Contracts & Commercial Advisory", "Drafting, negotiation and management of commercial agreements.", "contracts", "Part-14 .png"],
  ["Corporate Transactions", "Mergers, acquisitions, investments and strategic business transactions.", "corporate-transactions", "Part-16 .png"],
  ["Joint Ventures & Strategic Alliances", "Structuring and negotiating joint ventures, partnerships and alliances.", "corporate-advisory/joint-ventures", "Part-9 .png"],
  ["Business Strategy & Advisory", "Strategic planning, market entry and commercially focused growth advice.", "corporate-advisory/business-strategy", "Banking & Financial Services .png"],
  ["Corporate Restructuring", "Reorganisation, demerger, amalgamation and business transformation.", "corporate-advisory/corporate-restructuring", "Infrastructure & Projects .png"],
  ["Due Diligence", "Legal, commercial and regulatory due diligence for investments and transactions.", "corporate-transactions/due-diligence", "Part-18 .png"],
];
const lifecycle = [
  ["Establish", "Entity formation", "Structuring", "Shareholding", "business-formation"],
  ["Operate", "Contracts", "Governance", "Compliance", "contracts"],
  ["Grow", "Strategic advisory", "Joint ventures", "Business expansion", "corporate-advisory/business-strategy"],
  ["Transact", "M&A", "Investments", "Divestments", "corporate-transactions"],
  ["Restructure", "Reorganisation", "Amalgamation", "Demerger", "corporate-advisory/corporate-restructuring"],
  ["Comply", "Regulatory advisory", "Corporate governance", "Risk management", "regulatory-and-compliance"],
  ["Exit", "Exit strategy", "Business sale", "Transaction support", "startup-advisory/exit-strategy"],
];
const approach = [["document", "Understand", "Your objectives"], ["search", "Assess", "Opportunities & risks"], ["chart", "Strategise", "Practical solutions"], ["bulb", "Advise", "Expert guidance"], ["people", "Implement", "End-to-end support"], ["shield", "Deliver Value", "Long-term success"]];
function Action({ children, outline = false }: { children: React.ReactNode; outline?: boolean }) { return <Link href="/contact" className={`${styles.button} ${outline ? styles.outline : ""}`}>{children}<Icon name="arrow" /></Link>; }
function TextLink({ href, children }: { href: string; children: React.ReactNode }) { return <Link href={href} className={styles.textLink}>{children}<Icon name="arrow" /></Link>; }

export default function CorporateCommercial() {
  return <div className={styles.page}>
    <div className={styles.hero}><Image src="/Part-10 .png" alt="A contemporary corporate boardroom overlooking the city" fill preload sizes="100vw" /></div>
    <section className={styles.intro}><div className="container"><nav aria-label="Breadcrumb" className={styles.breadcrumb}><Link href="/">Home</Link><span>›</span><Link href="/services">Services</Link><span>›</span><span aria-current="page">Corporate & Commercial</span></nav><h1>Corporate & Commercial</h1><p className={styles.subtitle}>Strategic legal and business solutions for a stronger, more resilient enterprise.</p><p className={styles.description}>At Astronis Global, we advise businesses across the full spectrum of corporate and commercial matters — from structuring and governance to transactions, contracts and strategic growth. Our integrated approach helps organisations navigate complex business environments with clarity and confidence.</p></div></section>
    <section className={styles.capabilities} aria-labelledby="capabilities-heading"><div className="container"><h2 id="capabilities-heading">Our Corporate & Commercial Capabilities</h2><div className={styles.cardGrid}>{capabilities.map(([title, description, path, image]) => <Link href={`/services/${path}`} className={styles.card} key={path}><div className={styles.cardImage}><Image src={`/${image}`} alt="" fill sizes="(max-width: 600px) 100vw, (max-width: 1000px) 50vw, 25vw" /></div><div className={styles.cardBody}><h3>{title}</h3><p>{description}</p><span className={styles.textLink}>Learn more <Icon name="arrow" /></span></div></Link>)}</div></div></section>
    <section className={styles.growth}><Image src="/Real Estate & Construction .png" alt="" fill sizes="100vw" /><div className={`container ${styles.growthContent}`}><h2>Enabling Transactions.<br />Building Sustainable Growth.</h2><p>Comprehensive support for complex corporate<br className={styles.desktopBreak} /> and commercial objectives.</p><Action>Discuss Your Requirements</Action></div></section>
    <section className={styles.lifecycle} aria-labelledby="lifecycle-heading"><div className="container"><h2 id="lifecycle-heading">Support Across the Business Lifecycle</h2><ol>{lifecycle.map(([title, a, b, c, path]) => <li key={title}><Link href={`/services/${path}`}><span className={styles.dot} /><h3>{title}</h3><p>{a}<br />{b}<br />{c}</p></Link></li>)}</ol></div></section>

    <section className={styles.sectorSection}><div className="container"><div className={styles.sectionTop}><div><span className={styles.sectionLabel}>EXPERTISE IN YOUR WORLD</span><h2>Industries We Serve</h2><p>Commercial perspective shaped around the realities of your sector.</p></div><TextLink href="/industries">Explore all industries</TextLink></div><div className={styles.sectorCards}>{[industries[0], industries[1], industries[3], industries[4], industries[2], industries[5]].map((s, i) => <Link href={"/industries/" + s.slug} className={styles.sectorCard} key={s.slug}><Image src={s.image} alt="" fill sizes="(max-width: 600px) 100vw, (max-width: 1000px) 50vw, 33vw" /><span className={styles.sectorNumber}>0{i + 1}</span><div><h3>{s.title}</h3><span>Explore sector expertise <Icon name="arrow" /></span></div></Link>)}</div></div></section>
    <section className={styles.approachSection}><div className="container"><div className={styles.approachHeading}><div><span className={styles.sectionLabel}>A CLEAR PROCESS. A SHARED DIRECTION.</span><h2>Our Approach</h2></div><p>From the first conversation to implementation, we turn complex business questions into clear, actionable next steps.</p></div><ol className={styles.processCards}>{approach.map(([icon, title], i) => <li key={title}><div className={styles.processTop}><Icon name={icon} /><span>0{i + 1}</span></div><h3>{title}</h3><p>{["Understand your business priorities and define what success looks like.", "Examine the commercial context, identify risks and clarify your options.", "Build a practical roadmap aligned with your objectives and timelines.", "Bring together the right expertise for informed decisions.", "Coordinate documentation and execution with your team.", "Review progress and support your next stage of growth."][i]}</p></li>)}</ol><div className={styles.trustStrip}><span><Icon name="shield" /> Commercial perspective</span><span><Icon name="people" /> Multidisciplinary expertise</span><span><Icon name="chart" /> Long-term advisory partnership</span></div></div></section>
    <section className={styles.blogSection}><div className="container"><div className={styles.sectionTop}><div><span className={styles.sectionLabel}>IDEAS FOR YOUR NEXT BUSINESS DECISION</span><h2>Corporate & Commercial Insights</h2><p>Practical reading on structure, contracts, transactions and partnerships.</p></div></div><div className={styles.blogGrid}>{corporateArticles.map(article => <Link href={"/insights/" + article.slug} className={styles.blogCard} key={article.slug}><div className={styles.cardImage}><Image src={article.image} alt="" fill sizes="(max-width: 600px) 100vw, (max-width: 1000px) 50vw, 25vw" /></div><div className={styles.blogBody}><span className={styles.resourceCategory}>{article.category}</span><h3>{article.title}</h3><p>{article.excerpt}</p><span className={styles.textLink}>Read article <Icon name="arrow" /></span></div></Link>)}</div></div></section>
    <section className={styles.professionalSection}><div className="container"><div className={styles.sectionTop}><div><span className={styles.sectionLabel}>PEOPLE BEHIND THE ADVICE</span><h2>Our Professionals</h2><p>Meet the team supporting your legal, regulatory and commercial needs.</p></div><TextLink href="/professionals">Meet our team</TextLink></div><div className={styles.professionalGrid}>{professionals.map(p => <Link href={"/professionals/" + p.slug} className={styles.professionalCard} key={p.slug}><div className={styles.portrait}><Image src={p.image} alt={p.name} fill sizes="(max-width: 600px) 100vw, (max-width: 1000px) 50vw, 25vw" /></div><div><span className={styles.resourceCategory}>{p.role}</span><h3>{p.name}</h3><p>{p.expertise}</p><span className={styles.textLink}>View profile <Icon name="arrow" /></span></div></Link>)}</div></div></section>
    <section className={styles.faqSection}><div className={"container " + styles.faqLayout}><div><span className={styles.sectionLabel}>YOUR QUESTIONS, ANSWERED</span><h2>Frequently Asked Questions</h2><p>Understand how our corporate and commercial team can support your business.</p><TextLink href="/contact">Discuss your requirements</TextLink></div><div className={styles.faqList}>{[...serviceFaqs["corporate-advisory"], ["Do you support joint ventures and corporate restructuring?", "Yes. Our corporate advisory capabilities include joint venture structuring, partnership arrangements and corporate reorganisation. The scope is tailored to your business and proposed transaction."], ["What should I share for an initial discussion?", "Share a brief description of your business, the matter you need help with, your objectives and key timelines. Our team can then identify the information needed to scope the engagement."], ["Can you assist with ongoing corporate advisory?", "Yes. Contact our team to discuss recurring corporate, commercial and governance needs. We will agree the scope and working arrangements around your requirements."]].map(([question, answer]) => <details key={question}><summary>{question}<Icon name="chevron" /></summary><p>{answer}</p></details>)}</div></div></section>
    <section className={styles.cta}><Image src="/Real Estate & Construction .png" alt="" fill sizes="100vw" /><div className={`container ${styles.ctaInner}`}><div><h2>Let’s Build What’s Next, Together.</h2><p>Connect with our team for strategic legal and business solutions.</p></div><div className={styles.ctaActions}><Action>Speak to an Advisor</Action><Action outline>Submit an Enquiry</Action></div></div></section>
  </div>;
}
